### ISSUE TITLE
kong_api unexpected EOF

### ISSUE THREAD

**Issue by cludden** [kevholditch/terraform-provider-kong#34]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
- kong_api

### Terraform Configuration Files
```hcl
resource "kong_api" "player" {
  name = "${var.account}-${var.service_name}"

  uris = ["/xxxxxxx(/\\d+)*/?"]

  methods                  = ["GET"]
  upstream_url             = "http://${aws_s3_bucket.xxxxxx.website_endpoint}/"
  strip_uri                = true
  preserve_host            = false
  retries                  = 3
  upstream_connect_timeout = 60000
  upstream_send_timeout    = 30000
  upstream_read_timeout    = 10000
  https_only               = false
  http_if_terminated       = false
}
```

### Debug Output
```
2018/08/06 10:33:35 [DEBUG] Starting graph walk: walkApply
kong_api.player: Creating...
  http_if_terminated:       "" => "false"
  https_only:               "" => "false"
  methods.#:                "0" => "1"
  methods.0:                "" => "GET"
  name:                     "" => "xxxxxxx"
  preserve_host:            "" => "false"
  retries:                  "" => "3"
  strip_uri:                "" => "true"
  upstream_connect_timeout: "" => "60000"
  upstream_read_timeout:    "" => "10000"
  upstream_send_timeout:    "" => "30000"
  upstream_url:             "" => "xxxxxx"
  uris.#:                   "0" => "1"
  uris.0:                   "" => "/xxxxxx(/\\d+)*/?"
2018-08-06T10:33:35.627-0600 [DEBUG] plugin.terraform-provider-kong: panic: runtime error: invalid memory address or nil pointer dereference
2018-08-06T10:33:35.627-0600 [DEBUG] plugin.terraform-provider-kong: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x993aa9]
2018-08-06T10:33:35.627-0600 [DEBUG] plugin.terraform-provider-kong: 
2018-08-06T10:33:35.627-0600 [DEBUG] plugin.terraform-provider-kong: goroutine 42 [running]:
2018-08-06T10:33:35.627-0600 [DEBUG] plugin.terraform-provider-kong: github.com/kevholditch/terraform-provider-kong/kong.resourceKongApiCreate(0xc4203e6770, 0xabbd00, 0xc420169110, 0x24, 0xf5ea20)
2018-08-06T10:33:35.627-0600 [DEBUG] plugin.terraform-provider-kong: 	/home/travis/gopath/src/github.com/kevholditch/terraform-provider-kong/kong/resource_kong_api.go:109 +0x139
2018-08-06T10:33:35.627-0600 [DEBUG] plugin.terraform-provider-kong: github.com/kevholditch/terraform-provider-kong/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc4203ec3c0, 0xc420266320, 0xc42029cea0, 0xabbd00, 0xc420169110, 0xc42026cd01, 0xc420289b88, 0x4bbe7c)
2018-08-06T10:33:35.627-0600 [DEBUG] plugin.terraform-provider-kong: 	/home/travis/gopath/src/github.com/kevholditch/terraform-provider-kong/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:193 +0x372
2018-08-06T10:33:35.627-0600 [DEBUG] plugin.terraform-provider-kong: github.com/kevholditch/terraform-provider-kong/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc4202cf7a0, 0xc4202662d0, 0xc420266320, 0xc42029cea0, 0x18, 0x18, 0xc42029cee0)
2018-08-06T10:33:35.627-0600 [DEBUG] plugin.terraform-provider-kong: 	/home/travis/gopath/src/github.com/kevholditch/terraform-provider-kong/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:259 +0xa4
2018-08-06T10:33:35.627-0600 [DEBUG] plugin.terraform-provider-kong: github.com/kevholditch/terraform-provider-kong/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc420406ac0, 0xc42029ca80, 0xc42042e250, 0x0, 0x0)
2018-08-06T10:33:35.627-0600 [DEBUG] plugin.terraform-provider-kong: 	/home/travis/gopath/src/github.com/kevholditch/terraform-provider-kong/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:488 +0x57
2018-08-06T10:33:35.627-0600 [DEBUG] plugin.terraform-provider-kong: reflect.Value.call(0xc420150420, 0xc420168de8, 0x13, 0xb11859, 0x4, 0xc420289f18, 0x3, 0x3, 0xc42016e080, 0xc4202826e8, ...)
2018-08-06T10:33:35.627-0600 [DEBUG] plugin.terraform-provider-kong: 	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/reflect/value.go:447 +0x969
2018-08-06T10:33:35.627-0600 [DEBUG] plugin.terraform-provider-kong: reflect.Value.Call(0xc420150420, 0xc420168de8, 0x13, 0xc420282718, 0x3, 0x3, 0xc42020ef60, 0xc400000005, 0x0)
2018-08-06T10:33:35.627-0600 [DEBUG] plugin.terraform-provider-kong: 	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/reflect/value.go:308 +0xa4
2018-08-06T10:33:35.627-0600 [DEBUG] plugin.terraform-provider-kong: net/rpc.(*service).call(0xc420414340, 0xc420162b40, 0xc42037b240, 0xc42037b250, 0xc4203a1000, 0xc420407020, 0x9ea400, 0xc42029ca80, 0x16, 0x9ea440, ...)
2018-08-06T10:33:35.627-0600 [DEBUG] plugin.terraform-provider-kong: 	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/rpc/server.go:384 +0x14e
2018-08-06T10:33:35.627-0600 [DEBUG] plugin.terraform-provider-kong: created by net/rpc.(*Server).ServeCodec
2018-08-06T10:33:35.627-0600 [DEBUG] plugin.terraform-provider-kong: 	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/net/rpc/server.go:480 +0x43a

```

### Expected Behavior
I would expect a meaningful error if there is an issue creating the api

### Actual Behavior
nondescript EOF error which I believe stems from a nil pointer dereference caused by [this line](https://github.com/kevholditch/terraform-provider-kong/blob/master/kong/resource_kong_api.go#L105). Should it not be `if err != nil || api == nil` instead of `if err != nil && api != nil`?

### Steps to Reproduce
1. `terraform apply`

**Comment by kevholditch** [comment]
@cludden Yes you are correct that the if statement is not correct.  I will get that updated.  

Has your kong instance got restricted access ie locked down by api key?  If so then I think what is happening is that the create api request is getting a `403` which in the current version of `gokong` (the library used to talk to kong) returns a `nil` error and `nil` resource.  This is being fixed in a new version to return a non `nil` error in this case but in the meantime you may want to look to check you have setup the provider correctly (if it is locked down).

**Comment by kevholditch** [comment]
@cludden just relased version `v.1.7.0` which has the unauthorised fix and the fix that you correctly state in your issue.  If you give that a try and see if it resolves your issue.
